development:
  adapter: postgresql
#  database: mobiledeliverybackup_development
  database: mobiledelivery_livedb_backup
  username: postgres
  password: ubuntu
  host: localhost
  encoding: UTF8


test:
  adapter: postgresql
  database: mobiledeliverybackup_test
  username: postgres
  password: ubuntu
  host: localhost
  encoding: UTF8

#local DB == mobiledelivery_development
#backup of live DB will be in -->  mobiledelivery_livedb_backup


production:
  adapter: postgresql
#  database: mobiledeliverybackup_production
  database: mobiledelivery_development
  username: postgres
  password: ubuntu
  host: localhost
  encoding: UTF8
